# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
    #   uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Install dependencies
      run: go get .

    - name: Build
      run: go build -o cine-dots

    - name: Generate a coverage report
      run: go test -v -coverpkg=./pkg/handlers,./pkg/repositories ./tests/... -coverprofile=coverage.out
      continue-on-error: true

    - name: Coverage summary
      run: go tool cover -func=coverage.out

    - name: Install Keploy CLI
      run: |
        curl --silent -L https://keploy.io/ent/install.sh | bash
    
    - name: Start the Local Server in Backgroud
      run: ./cine-dots &

    - name: Run Keploy Test Suite
      run: |
        export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
        keploy test-suite --app=${{ secrets.KEPLOY_APP_ID }} --base-path http://localhost:9090/api/v1/ --cloud